var au=document.getElementById("au"),scroll=document.getElementById("scroll");
var lineEls=[].slice.call(document.querySelectorAll(".line[data-s]"));
var imls=[].slice.call(document.querySelectorAll(".iml"));var curImg=-1;
function setImg(n){if(!imls.length||n===curImg)return;curImg=n;for(var z=0;z<imls.length;z++)imls[z].classList.toggle("on",z===n);}
var SHORTS=document.documentElement.hasAttribute("data-shorts");
var IMGRUNS=[];(function(){var cur=null;for(var i=0;i<LINES.length;i++){var im=LINES[i].img||0;if(!cur||cur.img!==im){cur={img:im,start:LINES[i].start,end:LINES[i].end,k:IMGRUNS.length};IMGRUNS.push(cur);}else{cur.end=LINES[i].end;}LINES[i].run=cur;}})();
var curRun=-1,lastPanT=-9;
function setPan(idx,tt){if(!SHORTS||idx<0||!imls.length)return;var r=LINES[idx].run;if(!r)return;var el=imls[r.img];if(!el)return;var seek=Math.abs(tt-lastPanT)>1;lastPanT=tt;if(r.k===curRun&&!seek)return;curRun=r.k;
 var dur=Math.max(5,r.end-r.start+1.2),dir=r.k%2?"shPanR":"shPanL";
 el.style.animation="none";void el.offsetWidth;
 el.style.animation=dir+" "+dur.toFixed(2)+"s linear both";
 el.style.animationDelay=(-Math.max(0,tt-r.start)).toFixed(2)+"s";}
var cd=document.getElementById("countdown"),cdfg=document.querySelector(".cd-fg"),cdNum=document.getElementById("cdNum"),CDC=163.4,FS0=LINES.length?LINES[0].start:0;
var curLine=-1,started=false,aboutOpen=false,lyricsOpen=false,lastVol=1,narr=document.getElementById("narr"),narrPlaying=false,LEAD=0.18,OFFSET=(typeof SONG_OFFSET!=="undefined"?+SONG_OFFSET:0),INTRO=(typeof INTRO_START!=="undefined"?+INTRO_START:0);
LINES.forEach(function(L){L.w.forEach(function(o){o.s0=o.s;});});
function applyIntro(){var flat=[];LINES.forEach(function(L){L.w.forEach(function(o){flat.push(o);});});function done(){LINES.forEach(function(L){L.start=L.w[0].s;});FS0=LINES.length?LINES[0].start:0;}if(typeof INTRO_LINES!=="undefined"&&INTRO_LINES&&INTRO_LINES.length){var wi=0;for(var li=0;li<INTRO_LINES.length;li++){var n=INTRO_LINE_LENS[li]||0,s=INTRO_LINES[li][0],e=INTRO_LINES[li][1];for(var jj=0;jj<n&&wi<flat.length;jj++,wi++){flat[wi].s=+(s+(e-s)*(jj/Math.max(1,n))).toFixed(2);}}for(var i=wi;i<flat.length;i++)flat[i].s=flat[i].s0;done();return;}if(INTRO<=0){for(var i=0;i<flat.length;i++)flat[i].s=flat[i].s0;done();return;}var end=(typeof INTRO_TO!=="undefined"&&INTRO_TO>INTRO)?INTRO_TO:0;if(!end){var j=0;while(j<flat.length&&flat[j].s0<INTRO)j++;end=(j<flat.length)?flat[j].s0:(INTRO+(j||1)*0.45);}if(end<=INTRO)end=INTRO+1;var k=0;while(k<flat.length&&flat[k].s0<end)k++;if(k<=0){for(var i=0;i<flat.length;i++)flat[i].s=flat[i].s0;done();return;}var se;if(typeof INTRO_END!=="undefined"&&INTRO_END>INTRO){se=Math.min(INTRO_END,end);}else{var gaps=[];for(var i=k+1;i<flat.length;i++){var g=flat[i].s0-flat[i-1].s0;if(g>0.04&&g<1.5)gaps.push(g);}gaps.sort(function(a,b){return a-b;});var R=gaps.length?gaps[Math.floor(gaps.length/2)]:0.42;R=Math.min(0.8,Math.max(0.25,R))*1.1;se=Math.min(end,INTRO+k*R);}if(se<=INTRO)se=INTRO+0.5;for(var i=0;i<k;i++)flat[i].s=+(INTRO+(se-INTRO)*(i/k)).toFixed(2);for(var i=k;i<flat.length;i++)flat[i].s=flat[i].s0;done();}
var DCAP=/[?&]embed=1/.test(location.search)?30:0;
function fmt(t){t=Math.max(0,t|0);return (t/60|0)+":"+("0"+(t%60)).slice(-2);}
function startPlay(){if(started)return;started=true;au.play();var tt=document.getElementById("title");tt.classList.add("starting");setTimeout(function(){tt.classList.add("hide");},1500);}
function gateClick(e){if(e.target&&e.target.closest&&e.target.closest(".gate-x"))return;startPlay();}
document.addEventListener("keydown",function(e){if(e.code!=="Space"&&e.key!==" ")return;var t=e.target;if(t&&(t.tagName==="INPUT"||t.tagName==="TEXTAREA"||t.isContentEditable))return;e.preventDefault();if(e.repeat)return;if(!started){startPlay();return;}if(au.paused){au.play();}else{au.pause();}});
function togglePlay(){if(au.paused){au.play();}else{au.pause();}}
function seekTo(t){if(DCAP&&t>=DCAP)return;au.currentTime=t+0.01;if(au.paused&&started)au.play();}
function scrub(e){var r=document.getElementById("track").getBoundingClientRect();var dd=DCAP||(au.duration||1);au.currentTime=Math.max(0,Math.min(dd-0.05,(e.clientX-r.left)/r.width*dd));}
(function(){var tr=document.getElementById("track");if(!tr)return;var drag=false;function seekAt(x){var r=tr.getBoundingClientRect();var dd=DCAP||(au.duration||1);au.currentTime=Math.max(0,Math.min(dd-0.05,(x-r.left)/r.width*dd));}tr.addEventListener("pointerdown",function(e){drag=true;try{tr.setPointerCapture(e.pointerId);}catch(_){}seekAt(e.clientX);});tr.addEventListener("pointermove",function(e){if(drag)seekAt(e.clientX);});tr.addEventListener("pointerup",function(){drag=false;});tr.addEventListener("pointercancel",function(){drag=false;});})();
function skipSong(d){if(!PLAYLIST||PLAYLIST.length<2)return;var i=-1;for(var k=0;k<PLAYLIST.length;k++)if(PLAYLIST[k].id===SONG.id)i=k;var n=PLAYLIST[((i<0?0:i)+d+PLAYLIST.length)%PLAYLIST.length];location.href="../"+n.id+"/index.html?play=1";}
document.addEventListener("keydown",function(e){var t=e.target;if(t&&(t.tagName==="INPUT"||t.tagName==="TEXTAREA"||t.isContentEditable))return;if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();var dd=DCAP||(au.duration||0);if(dd)au.currentTime=Math.max(0,Math.min(dd-0.05,au.currentTime+(e.key==="ArrowRight"?5:-5)));}else if(e.key==="ArrowUp"||e.key==="ArrowDown"){e.preventDefault();var v=Math.max(0,Math.min(1,(+au.volume||0)+(e.key==="ArrowUp"?0.1:-0.1)));setVol(v);var vs=document.getElementById("vol");if(vs)vs.value=v;}});
function setVol(v){au.volume=+v;au.muted=false;volIcon();}
function toggleMute(){if(au.muted||au.volume===0){au.muted=false;au.volume=lastVol||1;document.getElementById("vol").value=au.volume;}else{lastVol=au.volume;au.muted=true;}volIcon();}
function volIcon(){var b=document.getElementById("volBtn");if(au.muted||au.volume===0){b.innerHTML=VOL.mute;}else if(au.volume<0.5){b.innerHTML=VOL.low;}else{b.innerHTML=VOL.on;}}
function toggleCollapse(){document.body.classList.toggle("pl-collapsed");}
var FSIC={enter:'<svg class="vi" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M9 4H4v5M15 4h5v5M9 20H4v-5M15 20h5v-5"/></svg>',exit:'<svg class="vi" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M4 9h5V4M20 9h-5V4M4 15h5v5M20 15h-5v5"/></svg>'};
function fsEl(){return document.fullscreenElement||document.webkitFullscreenElement||null;}
function toggleFs(){var d=document.documentElement;try{if(fsEl()){(document.exitFullscreen||document.webkitExitFullscreen).call(document);}else{(d.requestFullscreen||d.webkitRequestFullscreen).call(d);}}catch(_){}}
(function(){if(!(document.fullscreenEnabled||document.webkitFullscreenEnabled))return;var row=document.querySelector(".pl-right");if(!row)return;var b=document.createElement("button");b.id="fsBtn";b.className="ico";b.setAttribute("aria-label","Vollbild");b.title="Vollbild (f)";b.innerHTML=FSIC.enter;b.onclick=toggleFs;row.appendChild(b);function ic(){b.innerHTML=fsEl()?FSIC.exit:FSIC.enter;}document.addEventListener("fullscreenchange",ic);document.addEventListener("webkitfullscreenchange",ic);})();
document.addEventListener("keydown",function(e){if(e.key!=="f"&&e.key!=="F")return;var t=e.target;if(t&&(t.tagName==="INPUT"||t.tagName==="TEXTAREA"||t.isContentEditable))return;e.preventDefault();toggleFs();});
function openPl(){document.getElementById("plDrawer").hidden=false;document.getElementById("plBackdrop").hidden=false;}
function closePl(){document.getElementById("plDrawer").hidden=true;document.getElementById("plBackdrop").hidden=true;}
function togglePl(){if(document.getElementById("plDrawer").hidden)openPl();else closePl();}
au.addEventListener("ended",function(){try{if(typeof PLAYLIST!=="undefined"&&PLAYLIST.length){var i=-1;for(var k=0;k<PLAYLIST.length;k++){if(PLAYLIST[k].id===SONG_ID){i=k;break;}}if(i>=0&&i+1<PLAYLIST.length){location.href="../"+PLAYLIST[i+1].id+"/index.html?play=1";}}}catch(e){}});
var UI={es:{about:"La idea detrás",lyrics:"Letra",listen:"Escuchar"},de:{about:"Die Idee hinter dem Lied",lyrics:"Text",listen:"Anhören"}};
function updateLangUI(){var L=curLang(),f=FLAGS[L],n=L.toUpperCase();document.getElementById("flag").innerHTML=f;document.getElementById("langName").textContent=n;var bl=document.getElementById("aboutBtnLabel");if(bl)bl.textContent=UI[L].about;var ll=document.getElementById("lyricsLbl");if(ll)ll.textContent=UI[L].lyrics;var nl=document.getElementById("narrLbl");if(nl)nl.textContent=UI[L].listen;var gn=document.getElementById("gateName");if(gn)gn.textContent=(NAMES&&NAMES[L])?NAMES[L]:"";var ns=document.getElementById("nowSub");if(ns)ns.textContent=(NAMES&&NAMES[L])?NAMES[L]:"";var seg=document.querySelectorAll(".ab-lng");for(var i=0;i<seg.length;i++)seg[i].classList.toggle("on",seg[i].getAttribute("data-l")===L);}
function setTLang(l){document.documentElement.setAttribute("data-tlang",l);updateLangUI();closeMenus();if(narr&&!narr.paused)narr.pause();if(narr)narr.removeAttribute("data-src");if(aboutOpen)renderAbout();if(lyricsOpen)renderLyrics();}
function toggleLang(){setTLang(curLang()==="de"?"es":"de");}
function closeMenus(){var v=document.getElementById("volPop");if(v)v.hidden=true;var m=document.getElementById("langMenu");if(m)m.hidden=true;}
function toggleVolPop(e){e.stopPropagation();var m=document.getElementById("langMenu");if(m)m.hidden=true;var v=document.getElementById("volPop");v.hidden=!v.hidden;}
function toggleLangMenu(e){e.stopPropagation();var v=document.getElementById("volPop");if(v)v.hidden=true;var m=document.getElementById("langMenu");m.hidden=!m.hidden;}
document.addEventListener("click",function(e){if(!(e.target.closest&&e.target.closest(".popwrap")))closeMenus();});
function rowsOf(u){return u.rows||[{w:u.w,es:u.es,de:u.de}];}
function renderLyrics(){var L=curLang();document.getElementById("lyricsEyebrow").textContent=L==="de"?"Ganzer Text":"Letra completa";document.getElementById("lyricsTitle").textContent=SONG.title;var h="";for(var i=0;i<LINES.length;i++){var rs=rowsOf(LINES[i]);for(var r=0;r<rs.length;r++){var en=rs[r].w.map(function(o){return o.t;}).join(" ");if(!en)continue;var tr=rs[r][L]||"";var ww=rs[r].w,st=(ww&&ww[0]?ww[0].s:0),et=(ww&&ww.length?ww[ww.length-1].s:st);h+='<div class="ll"><div class="ll-en">'+en+"</div>"+(tr?('<div class="ll-tr">'+tr+"</div>"):"")+"</div>";}}document.getElementById("lyricsBody").innerHTML=h;}
function openLyrics(){lyricsOpen=true;renderLyrics();document.getElementById("lyricsModal").hidden=false;}
function closeLyrics(){lyricsOpen=false;document.getElementById("lyricsModal").hidden=true;}
function downloadPdf(){if(!(window.jspdf&&window.jspdf.jsPDF)){alert("PDF konnte nicht geladen werden (Internet noetig).");return;}var L=curLang();var doc=new window.jspdf.jsPDF({unit:"pt",format:"a4"});var W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),mx=56,y=74,mw=W-mx*2;doc.setFont("times","bold");doc.setFontSize(22);doc.setTextColor(20,20,20);doc.text(doc.splitTextToSize(SONG.title,mw),mx,y);y+=24;doc.setFont("helvetica","normal");doc.setFontSize(10);doc.setTextColor(120,120,120);doc.text(doc.splitTextToSize(SONG.refs||"",mw),mx,y);y+=28;var RW=[];for(var q=0;q<LINES.length;q++){var rs=rowsOf(LINES[q]);for(var rr=0;rr<rs.length;rr++)RW.push(rs[rr]);}for(var i=0;i<RW.length;i++){var en=RW[i].w.map(function(o){return o.t;}).join(" ");if(!en)continue;var tr=RW[i][L]||"";doc.setFont("times","normal");doc.setFontSize(13);var el=doc.splitTextToSize(en,mw);doc.setFont("times","italic");doc.setFontSize(10.5);var trl=tr?doc.splitTextToSize(tr,mw):[];var need=el.length*17+(trl.length?trl.length*14+8:0)+12;if(y+need>H-46){doc.addPage();y=62;}doc.setFont("times","normal");doc.setFontSize(13);doc.setTextColor(25,25,25);doc.text(el,mx,y);y+=el.length*17+3;if(trl.length){doc.setFont("times","italic");doc.setFontSize(10.5);doc.setTextColor(95,118,103);doc.text(trl,mx,y);y+=trl.length*14+12;}else{y+=8;}}doc.save(SONG.id+"-"+L+".pdf");}
function curLang(){return document.documentElement.getAttribute("data-tlang")==="de"?"de":"es";}
function renderAbout(){var L=curLang();document.getElementById("aboutEyebrow").textContent=L==="de"?"Über den Song":"Sobre la canción";document.getElementById("aboutTitle").textContent=SONG.title;document.getElementById("aboutRefs").textContent=SONG.refs||"";var h=(ABOUT.intro&&ABOUT.intro[L])?('<p class="ab-intro">'+ABOUT.intro[L]+"</p>"):"";var secs=(ABOUT&&ABOUT[L])||[];for(var i=0;i<secs.length;i++){h+='<div class="ab-sec"><div class="ab-h">'+secs[i].h+"</div>";var ps=secs[i].p||[];for(var j=0;j<ps.length;j++)h+='<div class="ab-p">'+ps[j]+"</div>";h+="</div>";}document.getElementById("aboutBody").innerHTML=h;}
function openAbout(){aboutOpen=true;renderAbout();document.getElementById("about").hidden=false;}
function closeAbout(){aboutOpen=false;document.getElementById("about").hidden=true;if(narr&&!narr.paused)narr.pause();}
function setNarrIcon(){var b=document.getElementById("narrBtn");if(b)b.querySelector(".ni").innerHTML=narrPlaying?NARRICON.pause:NARRICON.play;}
function toggleNarr(){var want="about-"+curLang()+".mp3";if(narr.getAttribute("data-src")!==want){narr.src=want;narr.setAttribute("data-src",want);}if(narr.paused){au.pause();var pr=narr.play();if(pr&&pr.catch)pr.catch(function(){});}else{narr.pause();}}
if(narr){narr.addEventListener("play",function(){narrPlaying=true;setNarrIcon();});narr.addEventListener("pause",function(){narrPlaying=false;setNarrIcon();});narr.addEventListener("ended",function(){narrPlaying=false;setNarrIcon();});}
document.addEventListener("keydown",function(e){if(e.key==="Escape"){closeAbout();closeLyrics();closeMenus();closePl();}});
au.addEventListener("play",function(){document.getElementById("pp").innerHTML="&#10073;&#10073;";});
au.addEventListener("pause",function(){document.getElementById("pp").innerHTML="&#9654;";});
au.addEventListener("loadedmetadata",function(){document.getElementById("dur").textContent=DCAP?(fmt(DCAP)+" demo"):fmt(au.duration);});
function setActive(i){if(i===curLine)return;curLine=i;
  for(var z=0;z<lineEls.length;z++){var le=lineEls[z];if(z<i){if(le.className!=="line done"){le.className="line done";var zw=le.querySelectorAll(".w");for(var q=0;q<zw.length;q++){zw[q].className="w sung";zw[q].style.removeProperty("--p");}}}else if(z>i){if(le.className!=="line"){le.className="line";var zw=le.querySelectorAll(".w");for(var q=0;q<zw.length;q++){zw[q].className="w";zw[q].style.removeProperty("--p");}}}}
  if(i>=0){var el=lineEls[i];el.className="line active";scroll.style.transform="translateY("+(-(el.offsetTop+el.offsetHeight/2))+"px)";}else if(lineEls[0]){scroll.style.transform="translateY("+(-(lineEls[0].offsetTop+lineEls[0].offsetHeight/2))+"px)";}}
function frame(){var t=au.currentTime,tt=t+LEAD-OFFSET,fs0=FS0+OFFSET;
  document.getElementById("cur").textContent=fmt(t);
  var _pf=((DCAP?Math.min(1,t/DCAP):(au.duration?t/au.duration:0))*100)+"%";document.getElementById("fill").style.width=_pf;var _kn=document.getElementById("knob");if(_kn)_kn.style.left=_pf;
  if(started&&fs0>0.6&&t<fs0-0.05){if(cd.hidden)cd.hidden=false;var cpr=Math.max(0,Math.min(1,t/fs0));cdfg.style.strokeDashoffset=(CDC*(1-cpr)).toFixed(1);cdNum.textContent=Math.max(1,Math.ceil(fs0-t));}else if(cd&&!cd.hidden){cd.hidden=true;}
  var idx=-1;for(var i=0;i<LINES.length;i++){if(tt>=LINES[i].start-0.15){idx=i;}else break;}
  setActive(idx);if(imls.length)setImg(idx>=0?(LINES[idx].img||0):0);setPan(idx,tt);
  if(idx>=0){var el=lineEls[idx],ws=el.querySelectorAll(".w"),L=LINES[idx].w,endT=LINES[idx].end;
    for(var k=0;k<ws.length;k++){var st=L[k]?L[k].s:0;var nx=(L[k+1]?L[k+1].s:endT);
      if(tt>=nx){if(ws[k].className!=="w sung"){ws[k].className="w sung";ws[k].style.removeProperty("--p");}}
      else if(tt>=st){if(ws[k].className!=="w cur")ws[k].className="w cur";var wl=(L[k]&&L[k].t?L[k].t.length:3),fd=Math.min(nx-st,Math.min(0.5,Math.max(0.08,wl*0.07))),p=fd>0?((tt-st)/fd):1;ws[k].style.setProperty("--p",(Math.max(0,Math.min(1,p))*100).toFixed(1)+"%");}
      else{if(ws[k].className!=="w"){ws[k].className="w";ws[k].style.removeProperty("--p");}}}}
  requestAnimationFrame(frame);}
applyIntro();updateLangUI();requestAnimationFrame(frame);
(function(){if(!/[?&]cal=1/.test(location.search))return;if(!(INTRO_END>0))INTRO_END=(typeof INTRO_TO!=="undefined"&&INTRO_TO>INTRO)?INTRO_TO:INTRO+10;var bar=document.createElement("div");bar.id="calbar";bar.style.cssText="position:fixed;left:12px;bottom:132px;z-index:80;background:rgba(7,13,24,.92);border:1px solid rgba(243,196,108,.55);border-radius:10px;padding:.5rem .65rem;color:#ffe7ad;font:600 .8rem Inter,system-ui,sans-serif;display:flex;gap:.55rem;align-items:center;box-shadow:0 8px 24px rgba(0,0,0,.4)";var bs="cursor:pointer;border:0;border-radius:6px;background:rgba(255,231,173,.18);color:#ffe7ad;font:inherit;padding:.2rem .5rem;font-size:1rem";function grp(lbl,id){return '<span style="opacity:.7;font-weight:400">'+lbl+'</span> <button data-t="'+id+'" data-d="-0.5" style="'+bs+'">&minus;</button><span id="'+id+'" style="min-width:46px;text-align:center;display:inline-block"></span><button data-t="'+id+'" data-d="0.5" style="'+bs+'">+</button>';}bar.innerHTML=grp("Start","cvs")+'<span style="opacity:.3">|</span>'+grp("Ende","cve");document.body.appendChild(bar);function upd(){document.getElementById("cvs").textContent=INTRO.toFixed(1)+"s";document.getElementById("cve").textContent=INTRO_END.toFixed(1)+"s";}function step(t,d){if(t==="cvs")INTRO=Math.max(0,+(INTRO+d).toFixed(2));else INTRO_END=Math.max(INTRO+0.5,+(INTRO_END+d).toFixed(2));applyIntro();upd();}bar.addEventListener("click",function(e){var t=e.target&&e.target.getAttribute("data-t"),d=e.target&&e.target.getAttribute("data-d");if(t&&d)step(t,+d);});document.addEventListener("keydown",function(e){if(e.target&&/INPUT|TEXTAREA/.test(e.target.tagName))return;if(e.key==="[")step("cvs",-0.1);else if(e.key==="]")step("cvs",0.1);else if(e.key===",")step("cve",-0.1);else if(e.key===".")step("cve",0.1);});upd();})();
(function(){try{var u=new URLSearchParams(location.search);if(u.get("play")==="1"){var p=au.play();if(p&&p.then){p.then(function(){started=true;var tt=document.getElementById("title");tt.classList.add("starting");setTimeout(function(){tt.classList.add("hide");},1400);}).catch(function(){});}}if(location.hash==="#about"){openAbout();}}catch(e){}})();
(function(){if(!/[?&]embed=1/.test(location.search))return;var a=document.getElementById("au");if(!a)return;a.addEventListener("timeupdate",function(){if(a.currentTime>=30){a.pause();}});})();
var c=document.getElementById("bg"),x=c.getContext("2d"),P=[];function rs(){c.width=innerWidth;c.height=innerHeight;}rs();addEventListener("resize",rs);for(var i=0;i<46;i++){P.push({x:Math.random()*c.width,y:Math.random()*c.height,r:Math.random()*1.8+0.4,v:Math.random()*0.25+0.05,a:Math.random()*0.5+0.2});}function dots(){x.clearRect(0,0,c.width,c.height);for(var i=0;i<P.length;i++){var p=P[i];p.y-=p.v;if(p.y<-5){p.y=c.height+5;p.x=Math.random()*c.width;}x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fillStyle="rgba(243,205,130,"+(p.a*1)+")";x.fill();}requestAnimationFrame(dots);}dots();